name: matomo_tracker_enhanced
description: A fully cross-platform wrap of the Matomo tracking client for
  Flutter, using the Matomo API.
version: 4.2.2
homepage: https://github.com/iliyami/matomo-tracker
repository: https://github.com/iliyami/matomo-tracker
issue_tracker: https://github.com/iliyami/matomo-tracker/issues
topics:
  - matomo
  - analytics

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.3.0"

dependencies:
  clock: ^1.1.1
  collection: ^1.17.2
  device_info_plus: ">=9.0.3 <11.0.0"
  flutter:
    sdk: flutter
  http: ^1.1.0
  package_info_plus: ">=4.1.0 <6.0.0"
  shared_preferences: ^2.2.2
  uuid: ^3.0.7

dev_dependencies:
  custom_lint: ^0.5.3
  fd_lints: ^2.2.0
  flutter_test:
    sdk: flutter
  meta: ^1.9.1
  mocktail: ^1.0.1

flutter: null
